"""Draft and post campaign replies to GitHub issues."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from octoscout.campaign.models import (
    CampaignIssue,
    DiagnosisRecord,
    ReplyRecord,
    VerificationRecord,
    append_jsonl,
    update_worklog,
)
from octoscout.models import Message, Role
from octoscout.prompts import load_prompt
from octoscout.providers.base import LLMProvider
from octoscout.search.github_client import GitHubClient

_REPLY_SYSTEM = load_prompt("campaign_reply_system")
_REPLY_TEMPLATE = load_prompt("campaign_reply_template")

_OCTOSCOUT_FOOTER = (
    "*Generated by [OctoScout](https://github.com/tommy-fcy/OctoScout)"
    " — AI-assisted ML compatibility diagnosis.*"
)

# Minimum delay between posts to avoid GitHub anti-spam
_POST_DELAY_SECONDS = 30


async def draft_reply(
    record: DiagnosisRecord,
    verification: VerificationRecord | None,
    provider: LLMProvider,
) -> str:
    """Draft a reply using the campaign template."""
    fix_actions_text = "\n".join(f"- `{a}`" for a in record.fix_actions) if record.fix_actions else "None"

    if verification and verification.verified:
        verif_text = (
            f"Verified ({verification.level}): broken_env={verification.broken_env} "
            f"→ {verification.broken_result}; fixed_env={verification.fixed_env} "
            f"→ {verification.fixed_result}"
        )
    elif verification:
        verif_text = f"Verification attempted ({verification.level}): {verification.broken_result}"
    else:
        verif_text = "Not verified"

    # Only cite evidence_sources (issues the diagnosis explicitly cited as
    # supporting the fix). related_issue_urls contains everything the agent
    # touched during search, which can include tangentially related issues.
    cited = record.evidence_sources[:3] if record.evidence_sources else []
    related = "\n".join(f"- {s}" for s in cited) if cited else "None"

    prompt = _REPLY_TEMPLATE.format(
        diagnosis_summary=record.diagnosis_summary[:2000],
        fix_actions=fix_actions_text,
        verification_section=verif_text,
        related_issues=related,
    )

    response = await provider.chat(
        [Message(role=Role.USER, content=prompt)],
        system=_REPLY_SYSTEM,
    )

    comment = (response.text or "").strip()

    # Ensure footer is present
    if _OCTOSCOUT_FOOTER not in comment:
        comment += f"\n\n---\n{_OCTOSCOUT_FOOTER}"

    return comment


async def check_already_replied(
    client: GitHubClient,
    repo: str,
    number: int,
) -> bool:
    """Check if OctoScout has already commented on this issue."""
    try:
        comments = await client.get_issue_comments(repo, number, per_page=30)
        for comment in comments:
            body = comment.get("body", "")
            if "OctoScout" in body and "AI-assisted ML compatibility" in body:
                return True
    except Exception:
        pass
    return False


async def check_issue_still_open(
    client: GitHubClient,
    repo: str,
    number: int,
) -> bool:
    """Verify the issue is still open before posting."""
    try:
        issue = await client.get_issue(repo, number)
        return issue.get("state") == "open"
    except Exception:
        return False


async def post_campaign_reply(
    record: DiagnosisRecord,
    issue: CampaignIssue,
    verification: VerificationRecord | None,
    provider: LLMProvider,
    client: GitHubClient,
    campaign_dir: Path,
    dry_run: bool = True,
) -> ReplyRecord:
    """Draft and optionally post a reply to a campaign issue.

    Safety checks:
    1. Issue must have has_concrete_fix=True
    2. Check for existing OctoScout comment (no double-posting)
    3. Verify issue is still open
    """
    now = datetime.now(timezone.utc).isoformat()
    verified = verification.verified if verification else False

    # Draft the reply
    comment_body = await draft_reply(record, verification, provider)

    reply_record = ReplyRecord(
        repo=issue.repo,
        number=issue.number,
        comment_body=comment_body,
        verified=verified,
    )

    if dry_run:
        reply_record.posted = False
        append_jsonl(campaign_dir / "replied.jsonl", reply_record)
        update_worklog(campaign_dir, issue, reply=reply_record)
        return reply_record

    # Safety checks before posting
    if await check_already_replied(client, issue.repo, issue.number):
        reply_record.posted = False
        reply_record.comment_body = "[SKIPPED: already replied]"
        append_jsonl(campaign_dir / "replied.jsonl", reply_record)
        return reply_record

    if not await check_issue_still_open(client, issue.repo, issue.number):
        reply_record.posted = False
        reply_record.comment_body = "[SKIPPED: issue closed]"
        append_jsonl(campaign_dir / "replied.jsonl", reply_record)
        return reply_record

    # Post the reply
    try:
        result = await client.post_comment(issue.repo, issue.number, comment_body)
        reply_record.posted = True
        reply_record.posted_at = now
        reply_record.comment_url = result.get("html_url", "")
    except Exception as e:
        reply_record.posted = False
        reply_record.comment_body = f"[POST FAILED: {e}]"

    append_jsonl(campaign_dir / "replied.jsonl", reply_record)
    update_worklog(campaign_dir, issue, reply=reply_record)
    return reply_record
